### PR TITLE
Tweak `result-container` styles

### PR DESCRIPTION
**Pull request by JungMinu**
**After** (Screenshot):
after_tweaks
Before (Screenshot):
before_styles
cc @joemccann

### CODE REVIEW

**Comment by JungMinu** [comment]
@tmpvar PTAL

**Comment by joemccann** [comment]
@pdevay please have a look a feel free to reject if you feel there is a more elegant solution that is trivial to implement in the short term.

**Comment by pdevay** [comment]
Upon reviewing this with @sarahmdarr we realized that the requirements for this redesign did not include making it responsive...so there is no design for mobile or large screens.

The design is working as intended for the majority of non-mobile screens (~800-1400px) other than some tweaks to spacing. I don't think it is beneficial or desirable to make this a fixed width layout for screens under 1400px because it's a big table.

Some tweaks that would help it scale better:

image
The score column should be a fixed width so it doesn't grow so wide

The only columns that need to scale are the name column and the author column

If we want to make a responsive version of the site it needs to be prioritized with everything else and designed first. As far as what that looks like, I'd like to just add scalable columns to the table that keep the table content 1400px wide centered (meaning the lines go edge to edge but the content stays 1400px wide).

**Comment by pdevay** [comment]
I'd like to add that making a responsive version of this before our platform UI seems really odd.

**Comment by joemccann** [comment]
My issue is, to _read_ a single row in the table, I have to read left-to-right across a ton of pixels which is counter to a reasonable reading experience.  Some UX studies have shown that when reading on a screen, the ideal width is definitely not 100% of the screen width.  I have zero interest in attempting to be pedantic or academic about this, I just know that my personal experience is poor when having to read across the full width of the page.

http://webstyleguide.com/wsg3/7-page-design/6-page-width-line-length.html

If this is a lack of priority relative to other bits, let's discuss that in a separate thread.  The issue here is that the full width for search results is a poor experience and I'd like to have this resolved and/or added to the backlog to be reviewed at the weekly Design review.  LMK thanks!

**Comment by pdevay** [comment]
The typographic best practice you're referencing is not in relation to tables; it's in relation to a single body of text. I try to keep all of our line lengths under 100 characters if possible. Within this screen there is a body of text in each column and even at max width on my screen the character count is adequate for each at the supported screen sizes.

As referenced above, adding a breakpoint for larger screen sizes seems necessary. Alternatively we could make scanning easier by removing some of the data on the list view and bumping up the type sizes for the important parts but we'd have to prioritize what needs to be kept (this was a 1:1 content transfer from the old version).

With that and the spacing fixes so there aren't huge caps between columns I think we'd be in better shape

**Comment by joemccann** [comment]
@pdevay that works for me!

**Comment by JungMinu** [comment]
@joemccann @pdevay fair enough, that works for me too 👍

**Comment by JungMinu** [comment]
so, updated based on @pdevay comments.

**Comment by pdevay** [comment]
Hrmmm not quite there; the layout should still be full width (100%) at screens <= 1400px wide

this is even less responsive than it was before. we'll probably need to actually design the layouts at the required breakpoints to make it fully responsive but @sarahmdarr & @k8k do you have any thoughts on the above in the meantime?

**Comment by sarahmdarr** [comment]
@JungMinu I am going to create a design for screens > 1401px and get that to you today. I will make a few other slight adjustments for you as well.

cc @pdevay

**Comment by JungMinu** [comment]
@pdevay oops, sorry, it was a mistake! will update it to be full width (100%) at screens <= 1400px wide.

**Comment by JungMinu** [comment]
@sarahmdarr In regards to your new design(https://zpl.io/1FDCUL), I think it should be 1400px wide centered according to @pdevay comments... thoughts?


> As far as what that looks like, I'd like to just add scalable columns to the table that keep the table content 1400px wide centered

**Comment by JungMinu** [comment]
@pdevay so I updated it to be responsive!

**Comment by sarahmdarr** [comment]
@JungMinu Correct. The design is created to be 1400px max width centered. We also want the nav to be max width of 1400. There are a few columns that will not grow larger though. The only columns that need to scale are the name column and the author column. 

There should also not be a border around the whole section and the dividers between each listing should be 100% to the screen.

**Comment by pdevay** [comment]
@JungMinu < 1400 looks good again 👍  if you can update the > 1400px screen to match @sarahmdarr 's design I think we're good

**Comment by JungMinu** [comment]
@pdevay @sarahmdarr Done, please review

**Comment by sarahmdarr** [comment]
@JungMinu Better, we can do further tweaking later on. The one thing that still needs to be fixed is the nav. It should have a max-width of 1400px please.

**Comment by JungMinu** [comment]
@sarahmdarr Updated, PTAL again.

**Comment by pdevay** [comment]
@JungMinu if you add this to the `header` it should be good to go until we can design a fully responsive version:

```
max-width: 1400px;
margin: 0 auto;
width: 100%;
```

edit: you may have done that Sorry...looking now

**Comment by pdevay** [comment]
That's what I get for leaving comments un-sent.

LGTM!

**Comment by JungMinu** [comment]
@pdevay Yes sir, Done. Thanks 😄

**Pull request merged**
